version: '3.8'

services:
  fxproxy:
    build: .
    ports:
      - "80:80"
    environment:
      - REMOTE=http://10.10.0.2:30120  # Change this to your FiveM server IP:port
    volumes:
      - ./cache:/srv/cache
    restart: unless-stopped