version: '3.8'

services:
  nginx-proxy:
    build: .
    ports:
      - "3128:3128"
    environment:
      - REMOTE=http://127.0.0.1:30120  # Change this to your remote server
    volumes:
      - ./cache:/srv/cache
      - ./logs:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3128/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s